import type { Achievement } from "@/entities/achievement";

// 実績の初期データ
export const DEFAULT_ACHIEVEMENTS: Omit<Achievement, "id" | "createdAt">[] = [
	// ログイン系実績
	{
		category: "login",
		name: "初めての一歩",
		description: "初めてログインする",
		iconUrl: null,
		conditionType: "total_logins",
		conditionValue: 1,
		conditionSubValue: null,
		rewardExp: 10,
		points: 10,
		sortOrder: 1,
		isActive: true,
	},
	{
		category: "login",
		name: "継続は力なり",
		description: "3日連続でログインする",
		iconUrl: null,
		conditionType: "login_streak",
		conditionValue: 3,
		conditionSubValue: null,
		rewardExp: 30,
		points: 20,
		sortOrder: 2,
		isActive: true,
	},
	{
		category: "login",
		name: "週間マスター",
		description: "7日連続でログインする",
		iconUrl: null,
		conditionType: "login_streak",
		conditionValue: 7,
		conditionSubValue: null,
		rewardExp: 50,
		points: 30,
		sortOrder: 3,
		isActive: true,
	},
	{
		category: "login",
		name: "月間マスター",
		description: "30日連続でログインする",
		iconUrl: null,
		conditionType: "login_streak",
		conditionValue: 30,
		conditionSubValue: null,
		rewardExp: 200,
		points: 100,
		sortOrder: 4,
		isActive: true,
	},
	{
		category: "login",
		name: "ベテラン冒険者",
		description: "合計50日ログインする",
		iconUrl: null,
		conditionType: "total_logins",
		conditionValue: 50,
		conditionSubValue: null,
		rewardExp: 100,
		points: 50,
		sortOrder: 5,
		isActive: true,
	},

	// ゲーム系実績
	{
		category: "game",
		name: "ルーレット初心者",
		description: "ルーレットを初めて回す",
		iconUrl: null,
		conditionType: "roulette_plays",
		conditionValue: 1,
		conditionSubValue: null,
		rewardExp: 10,
		points: 10,
		sortOrder: 10,
		isActive: true,
	},
	{
		category: "game",
		name: "幸運の女神",
		description: "レジェンダリーアイテムを獲得する",
		iconUrl: null,
		conditionType: "roulette_legendary",
		conditionValue: 1,
		conditionSubValue: null,
		rewardExp: 100,
		points: 50,
		sortOrder: 11,
		isActive: true,
	},
	{
		category: "game",
		name: "反射神経",
		description: "ミニゲームで1000点を獲得する",
		iconUrl: null,
		conditionType: "mini_game_score",
		conditionValue: 1000,
		conditionSubValue: null,
		rewardExp: 50,
		points: 30,
		sortOrder: 20,
		isActive: true,
	},
	{
		category: "game",
		name: "電光石火",
		description: "ミニゲームで2000点を獲得する",
		iconUrl: null,
		conditionType: "mini_game_score",
		conditionValue: 2000,
		conditionSubValue: null,
		rewardExp: 100,
		points: 50,
		sortOrder: 21,
		isActive: true,
	},
	{
		category: "game",
		name: "パーフェクトプレイヤー",
		description: "ミニゲームでパーフェクトスコア（全て300ms以内）を達成する",
		iconUrl: null,
		conditionType: "mini_game_perfect",
		conditionValue: 1,
		conditionSubValue: null,
		rewardExp: 150,
		points: 100,
		sortOrder: 22,
		isActive: true,
	},

	// コレクション系実績
	{
		category: "collection",
		name: "コレクター",
		description: "10個のアイテムを集める",
		iconUrl: null,
		conditionType: "items_collected",
		conditionValue: 10,
		conditionSubValue: null,
		rewardExp: 30,
		points: 20,
		sortOrder: 30,
		isActive: true,
	},
	{
		category: "collection",
		name: "レアハンター",
		description: "レアアイテムを5個集める",
		iconUrl: null,
		conditionType: "items_collected_rarity",
		conditionValue: 5,
		conditionSubValue: "rare",
		rewardExp: 50,
		points: 30,
		sortOrder: 31,
		isActive: true,
	},
	{
		category: "collection",
		name: "エピックコレクター",
		description: "エピックアイテムを3個集める",
		iconUrl: null,
		conditionType: "items_collected_rarity",
		conditionValue: 3,
		conditionSubValue: "epic",
		rewardExp: 100,
		points: 50,
		sortOrder: 32,
		isActive: true,
	},
	{
		category: "collection",
		name: "レジェンドコレクター",
		description: "レジェンダリーアイテムを1個集める",
		iconUrl: null,
		conditionType: "items_collected_rarity",
		conditionValue: 1,
		conditionSubValue: "legendary",
		rewardExp: 200,
		points: 100,
		sortOrder: 33,
		isActive: true,
	},

	// レベル系実績
	{
		category: "level",
		name: "初級冒険者",
		description: "レベル5に到達する",
		iconUrl: null,
		conditionType: "level_reached",
		conditionValue: 5,
		conditionSubValue: null,
		rewardExp: 50,
		points: 20,
		sortOrder: 40,
		isActive: true,
	},
	{
		category: "level",
		name: "中級冒険者",
		description: "レベル10に到達する",
		iconUrl: null,
		conditionType: "level_reached",
		conditionValue: 10,
		conditionSubValue: null,
		rewardExp: 100,
		points: 50,
		sortOrder: 41,
		isActive: true,
	},
	{
		category: "level",
		name: "上級冒険者",
		description: "レベル25に到達する",
		iconUrl: null,
		conditionType: "level_reached",
		conditionValue: 25,
		conditionSubValue: null,
		rewardExp: 200,
		points: 100,
		sortOrder: 42,
		isActive: true,
	},
	{
		category: "level",
		name: "マスター冒険者",
		description: "レベル50に到達する",
		iconUrl: null,
		conditionType: "level_reached",
		conditionValue: 50,
		conditionSubValue: null,
		rewardExp: 500,
		points: 200,
		sortOrder: 43,
		isActive: true,
	},

	// 特別実績
	{
		category: "special",
		name: "経験値マスター",
		description: "合計10000経験値を獲得する",
		iconUrl: null,
		conditionType: "exp_earned",
		conditionValue: 10000,
		conditionSubValue: null,
		rewardExp: 300,
		points: 150,
		sortOrder: 50,
		isActive: true,
	},
	{
		category: "special",
		name: "ゲームマスター",
		description: "ミニゲームを50回プレイする",
		iconUrl: null,
		conditionType: "mini_game_plays",
		conditionValue: 50,
		conditionSubValue: null,
		rewardExp: 200,
		points: 100,
		sortOrder: 51,
		isActive: true,
	},
];
